server {
    listen 80;
    server_name malshare.com;

    # Static exports
    location /exports/ {
        root /usr/share/nginx;
        autoindex off;  # optional: set to 'on' if you want directory listing
    }

    # PHP web app
    location / {
        proxy_pass http://web:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
