version: '3'
services:
  mysql:
    image: mysql:5.7.35
    container_name: malshare_db
    volumes:
      - ../malshare_db.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - MYSQL_ROOT_PASSWORD=this_is_not_the_prod_password
      - MYSQL_DATABASE=malshare_db
    ports:
      - "3306:3306"

  webserver:
    image: php:8.2-apache
    links:
      - "mysql"
    container_name: malshare_web
    volumes:
      - ./testing/samples:/mw/repository/binaries/
      - ./testing/uploads:/mw/uploads/
      - ../:/var/www/
    environment:
      MALSHARE_SAMPLES_ROOT: "/mw/repository/binaries/"
      MALSHARE_UPLOAD_SAMPLES_ROOT: "/mw/uploads/"
      MALSHARE_DB_HOST: "malshare_db"
      MALSHARE_DB_USER: "root"
      MALSHARE_DB_PASS: "this_is_not_the_prod_password"
      MALSHARE_DB_DATABASE: malshare_db

      MALSHARE_RECAPTCHA_SECRET: "DISABLED"
      MALSHARE_MAILGUN_USERNAME: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      MALSHARE_MAILGUN_PASSWORD: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      MALSHARE_MAILGUN_FROM: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      MALSHARE_MAILGUN_SMTP: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      MALSHARE_MAILGUN_PORT: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

      VT_CONTEXT_KEY: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      VT_CONTEXT_URL: "https://www.virustotal.com/api/v3/widget/url?mode=standalone&query="
      WASABI_ENDPOINT:  "http://s3:80"
      WASABI_REGION: "local"
      WASABI_KEY: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      WASABI_SECRET: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      WASABI_BUCKET: "malshare-samples"


    command: "/bin/sh -c 'docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable pdo_mysql && exec apache2-foreground'"
#    command: "/bin/sh -c 'docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable pdo_mysql && cd /var/www/ && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && apt update && apt install zip && composer install && exec apache2-foreground'"



    ports:
      - "8080:80"
